# Generated by Django 2.2.17 on 2020-11-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20201118_1353"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hkjk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nhg78686867", models.BigIntegerField()),
            ],
        ),
    ]
